# Generated by Django 3.1 on 2020-09-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
