# Generated by Django 3.1.2 on 2020-10-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201013_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.CharField(default='aman', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(default='chandnda', max_length=50),
            preserve_default=False,
        ),
    ]
